vision_api_key : AIzaSyALftPdGGJLIcS1brbBxseL0DUYioDh5uU
GOOGLE_APPLICATION_CREDENTIALS : "/Users/sarahkirk/turing/4module/gneiss-rocks/config/gneiss_rocks_credentials.json"
# bucket_name: "gneiss-rocks"
# access_key: 'AKIAJPB3JMSVDSJF6IXQ'
# secret_key: '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'
# region: 'us-east-2'
