vision_api_key : 17debb6c153a90472ab032b1e3fe21fc076a3b99
GOOGLE_APPLICATION_CREDENTIALS : "/Users/sarahkirk/turing/4module/gneiss-rocks/config/gneiss_rocks_credentials.json"
bucket_name: "gneiss-rocks"
access_key: 'AKIAJPB3JMSVDSJF6IXQ'
secret_key: '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'
region: 'us-east-2'
